# Generated by Django 4.2 on 2026-02-17 19:08

from django.db import migrations, models


def set_existing_users_verified(apps, schema_editor):
    """Set all existing users as email-verified so they aren't locked out."""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(is_email_verified=True)


def reverse_set_existing_users_verified(apps, schema_editor):
    """Reverse: do nothing (we can't know who was originally unverified)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        # Set all existing users as verified
        migrations.RunPython(
            set_existing_users_verified,
            reverse_set_existing_users_verified,
        ),
    ]

