# Generated by Django 4.2 on 2026-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on Delivery')], default='PREPAID', max_length=20),
        ),
    ]
