# Generated by Django 6.0 on 2025-12-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_at_website',
            field=models.BooleanField(default=True),
        ),
    ]
