# Generated by Django 4.2 on 2026-02-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_10_product_image_5_product_image_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Optional Amazon product link', max_length=500, null=True),
        ),
    ]
