# Generated by Django 4.2 on 2026-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_amazon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_out_of_stock',
            field=models.BooleanField(default=False, help_text='Manually mark product as out of stock regardless of quantity'),
        ),
    ]
