# Generated by Django 4.2 on 2026-02-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(blank=True, db_index=True, help_text='Blue Dart Air Waybill tracking number', max_length=20, null=True, unique=True)),
                ('pickup_token', models.CharField(blank=True, help_text='Pickup registration token from Blue Dart', max_length=20, null=True)),
                ('product_code', models.CharField(default='D', help_text='D=Domestic Priority, A=Apex, E=Surfaceline', max_length=1)),
                ('sub_product_code', models.CharField(default='P', help_text='P=Prepaid, C=COD', max_length=1)),
                ('origin_area', models.CharField(help_text='3-character origin area code (e.g., BOM, BLR)', max_length=3)),
                ('destination_area', models.CharField(blank=True, help_text='3-character destination area code from Blue Dart', max_length=3, null=True)),
                ('destination_pincode', models.CharField(max_length=6)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Actual or volumetric weight in kg', max_digits=5)),
                ('declared_value', models.DecimalField(decimal_places=2, help_text='Invoice value for insurance', max_digits=10)),
                ('collectible_amount', models.DecimalField(decimal_places=2, default=0, help_text='COD amount (0 for prepaid orders)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('rto_initiated', 'RTO Initiated'), ('rto_delivered', 'Returned to Origin'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('label_pdf', models.FileField(blank=True, null=True, upload_to='shipping/labels/%Y/%m/')),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, help_text='When shipment was picked up by Blue Dart', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Actual delivery timestamp', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last API error message for troubleshooting', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(help_text='Date and time of this tracking event')),
                ('scan_code', models.CharField(help_text='Blue Dart internal scan code', max_length=10)),
                ('scan_description', models.TextField(help_text='Human-readable event description')),
                ('scanned_location', models.CharField(help_text='Hub/facility name where scan occurred', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions or notes from Blue Dart', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['shipment', '-scan_date'], name='shipping_tr_shipmen_ac001a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackingevent',
            unique_together={('shipment', 'scan_date', 'scan_code', 'scanned_location')},
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='shipping_sh_status_58d901_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['awb_number'], name='shipping_sh_awb_num_33ed04_idx'),
        ),
    ]
