"""
Django settings for lefoyer project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yoursecretkey'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'www.lefoyerglobal.com', 'lefoyerglobal.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'products',
    'accounts',
    'cart',
    'orders',
    'wishlist',
    'reviews',
    'django_filters',
    'coupons',
    'shipping',
    'django_celery_beat',
]

JAZZMIN_SETTINGS = {
    "site_title": "Le foyeR. Admin",
    "site_header": "Le foyeR.",
    "site_brand": "Le foyeR.",
    "welcome_sign": "Welcome to Le foyeR. Admin",
    "copyright": "Le foyeR. Global",
    "site_logo": None,
    "custom_css": "/home/samikpandit/scpl/lefoyer-ecommerce/backend/static/admin/css/custom.css",
    "custom_links": {
        "orders": [{
            "name": "Sales Analytics",
            "url": "/admin/orders/analytics/",
            "icon": "fas fa-chart-line",
        }]
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lefoyer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lefoyer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "https://www.lefoyerglobal.com",
    "https://lefoyerglobal.com",
    "http://localhost:3000",  # For local development
]

CSRF_TRUSTED_ORIGINS = [
    "https://www.lefoyerglobal.com",
    "https://lefoyerglobal.com",
]

import os
from dotenv import load_dotenv

load_dotenv()

# PhonePe Configuration
PHONEPE_ENV = os.getenv('PHONEPE_ENV', 'SANDBOX')

if PHONEPE_ENV == 'PRODUCTION':
    PHONEPE_MERCHANT_ID = os.getenv('PHONEPE_PROD_MERCHANT_ID')
    PHONEPE_SALT_KEY = os.getenv('PHONEPE_PROD_SALT_KEY')
    PHONEPE_SALT_INDEX = int(os.getenv('PHONEPE_PROD_SALT_INDEX', 1))
else:
    # Use standard UAT credentials if not provided in env
    PHONEPE_MERCHANT_ID = os.getenv('PHONEPE_TEST_MERCHANT_ID', 'PGTESTPAYUAT')
    PHONEPE_SALT_KEY = os.getenv('PHONEPE_TEST_SALT_KEY', '099eb0cd-02cf-4e2a-8aca-3e6c6aff0399')
    PHONEPE_SALT_INDEX = int(os.getenv('PHONEPE_TEST_SALT_INDEX', 1))

PHONEPE_CALLBACK_URL = os.getenv("PHONEPE_CALLBACK_URL", "http://localhost:8000/api/orders/payment/callback/")

SITE_URL = os.getenv("SITE_URL", "http://localhost:5173")
API_URL = os.getenv("API_URL", "http://localhost:8000")

# ============================================================================
# CELERY Configuration
# ============================================================================
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

# Celery Beat Schedule
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'register-daily-pickup': {
        'task': 'shipping.tasks.register_daily_pickup',
        'schedule': crontab(hour=16, minute=0),  # 4:00 PM IST daily
    },
    'poll-active-shipments': {
        'task': 'shipping.tasks.poll_active_shipments',
        'schedule': crontab(minute=0, hour='*/2'),  # Every 2 hours
    },
}

# ============================================================================
# BLUE DART SHIPPING Configuration
# ============================================================================

# Blue Dart API Credentials
BLUEDART_LOGIN_ID = os.getenv('BLUEDART_LOGIN_ID', '')
BLUEDART_LICENCE_KEY = os.getenv('BLUEDART_LICENCE_KEY', '')
BLUEDART_CUSTOMER_CODE = os.getenv('BLUEDART_CUSTOMER_CODE', '')
BLUEDART_COD_CUSTOMER_CODE = os.getenv('BLUEDART_COD_CUSTOMER_CODE', '')
BLUEDART_TRACKING_LICENCE_KEY = os.getenv('BLUEDART_TRACKING_LICENCE_KEY', BLUEDART_LICENCE_KEY)

# Warehouse/Origin Details
BLUEDART_ORIGIN_AREA = os.getenv('BLUEDART_ORIGIN_AREA', 'BOM')
BLUEDART_ORIGIN_PINCODE = os.getenv('BLUEDART_ORIGIN_PINCODE', '400001')
BLUEDART_WAREHOUSE_NAME = os.getenv('BLUEDART_WAREHOUSE_NAME', 'Le Foyer Warehouse')
BLUEDART_WAREHOUSE_ADDRESS = os.getenv('BLUEDART_WAREHOUSE_ADDRESS', '')
BLUEDART_WAREHOUSE_CONTACT = os.getenv('BLUEDART_WAREHOUSE_CONTACT', 'Warehouse Manager')
BLUEDART_WAREHOUSE_PHONE = os.getenv('BLUEDART_WAREHOUSE_PHONE', '')

# Return Details
BLUEDART_RETURN_ADDRESS = os.getenv('BLUEDART_RETURN_ADDRESS', BLUEDART_WAREHOUSE_ADDRESS)
BLUEDART_RETURN_PINCODE = os.getenv('BLUEDART_RETURN_PINCODE', BLUEDART_ORIGIN_PINCODE)
BLUEDART_RETURN_CONTACT = os.getenv('BLUEDART_RETURN_CONTACT', 'Returns Desk')
BLUEDART_RETURN_PHONE = os.getenv('BLUEDART_RETURN_PHONE', BLUEDART_WAREHOUSE_PHONE)

# Environment
BLUEDART_DEMO_MODE = os.getenv('BLUEDART_DEMO_MODE', 'True').lower() == 'true'
BLUEDART_TRACKING_POLL_INTERVAL = 120  # minutes

# Default product settings for beauty products (lightweight parcels)
BLUEDART_DEFAULT_PRODUCT_CODE = 'D'  # Domestic Priority (fast delivery)
BLUEDART_DEFAULT_SUB_PRODUCT_CODE = 'P'  # Prepaid
BLUEDART_DEFAULT_PACK_TYPE = 'N'  # Non-Documents
BLUEDART_DEFAULT_WEIGHT_KG = float(os.getenv('BLUEDART_DEFAULT_WEIGHT_KG', '0.5'))
BLUEDART_DEFAULT_LENGTH_CM = float(os.getenv('BLUEDART_DEFAULT_LENGTH_CM', '20'))
BLUEDART_DEFAULT_WIDTH_CM = float(os.getenv('BLUEDART_DEFAULT_WIDTH_CM', '15'))
BLUEDART_DEFAULT_HEIGHT_CM = float(os.getenv('BLUEDART_DEFAULT_HEIGHT_CM', '10'))

